#!/usr/bin/env bash
#
# Applies or reverts the client-mode WiFi config for wlan0. The config file
# itself is generated by wifi.py (so SSID/password get safely escaped there)
# and handed to this script as a path to copy into place — this script only
# does the privileged part: installing it under /etc/netplan and applying.
#
# Usage: wifi-connect.sh apply <path-to-yaml> | revert

set -euo pipefail

ACTION="$1"
NETPLAN_WIFI_FILE="/etc/netplan/90-cloud-upload-wifi.yaml"

case "$ACTION" in
  apply)
    SRC="$2"
    install -m 600 "$SRC" "$NETPLAN_WIFI_FILE"
    netplan apply
    ;;
  revert)
    rm -f "$NETPLAN_WIFI_FILE"
    netplan apply
    ;;
  *)
    echo "Usage: $0 apply <path-to-yaml> | revert" >&2
    exit 1
    ;;
esac
